### PR TITLE
Add environment (reader-monad behaviour)

### PR DESCRIPTION
**Pull request by appetere**
Added reader-monad behaviour to the Isotope delegate.  Now has signature:

`public delegate IsotopeState<A> Isotope<Env, A>(Env env, IsotopeState state);`

**Updates**
These properties had to be converted to methods, to support the generic parameter:

- get
- unitM
- url
- webDriver
- getScreenShot
- disposeWebDriver
- defaultWait
- defaultInteval
- popLog

Fixed careers test, to expect "/jobs-at-meddbase/" instead of "careers"
Switched to use "Selenium.WebDriver.ChromeDriver" nuget package
Set AssemblyTitle to "Isotope80"
	
**Additions**

- public static Isotope<Env, Env> ask<Env>()
- public static Isotope<Env, R> asks<Env, R>(Func<Env, R> f)
- public static Isotope<Env, Unit> setWindowSize<Env>(Size size) 
- Environment tests

**Observations**

- waitUntilClickable does not use its "timeout" parameter

### CODE REVIEW

**Comment by colethecoder** [comment]
This change is much needed, injecting IO into the monad solves so many config problems and improves many non-unit test use cases. My reluctance to do this previously has been due to the type leakiness of it. I really liked the clean syntax:

```cs
from _1 in log("Update Window Size")
from _2 in setWindowSize(1280,960)
from _3 in nav("https://www.meddbase.com")
select unit
```

Which now becomes:

```cs
from _1 in log<Unit>("Update Window Size")
from _2 in setWindowSize<Unit>(1280,960)
from _3 in nav<Unit>("https://www.meddbase.com")
select unit
```

None of those functions use the Env and yet are polluted by it. My ideal approach would be that you ignore Env until your use-case needs it.

We could supplement the delegate with an environment-less one i.e.

```cs
public delegate IsotopeState<A> Isotope<Env, A>(Env env, IsotopeState state);
public delegate IsotopeState<A> Isotope<A>(IsotopeState state);
```

By doing this we could return most of the basic functions like `nav` back to their original form without an Env:

```cs
public static Isotope<Unit> nav(string url)
```

This then leaves you with the composability problem, particularly in LINQ, we can't mash `Isotope<Env, A>` and `Isotope<A>` together. For example this won't work:

```cs
public Isotope<MyIO, Unit> DoStuff =>
    from _1 in nav("https://www.meddbase.com")
    from _2 in doSomethingAmazing
    select unit;

public Isotope<MyIO, Unit> doSomethingAmazing => ...
```

We could make an adapter like:

```cs
public static Isotope<TEnv, A> WithEnv<TEnv, A>(this Isotope<A> iso) =>
    (env, sa) =>
    {
        var a = iso(sa);
        return new IsotopeState<A>(a.Value, a.State);
     };
```

this would enable:

```cs
public Isotope<MyIO, Unit> DoStuff =>
    from _1 in nav("https://www.meddbase.com").WithEnv<MyIO, Unit>()
    from _2 in doSomethingAmazing
    select unit;

public Isotope<MyIO, Unit> doSomethingAmazing => ...
```

which is pretty ugly but means that when you can work without the environment except when you need it.

Consumers of Isotope could create a slightly nicer extension:

```cs
public static Isotope<MyIO, A> WithEnv<A>(this Isotope<A> iso) => iso.WithEnv<MyIO, A>();
```

This reduces it to:

```cs
public Isotope<MyIO, Unit> DoStuff =>
    from _1 in nav("https://www.meddbase.com").WithEnv()
    from _2 in doSomethingAmazing
    select unit;

public Isotope<MyIO, Unit> doSomethingAmazing => ...
```

What do you think? How ugly would the `WithEnv` approach end up in your current project?

**Comment by appetere** [comment]
Could we use a sort of decorator pattern to create the simpler delegate?  So if you don't need the environment, everything is clean as before.  If you do need the environment, you will have to deal with the extra type-parameter everywhere (until we add a code-gen version maybe..?)

```csharp
namespace Isotope80
{
    public delegate IsotopeState<A> Isotope<A>(IsotopeState state);

    public static partial class Isotope
    {
        public static (IsotopeState state, A value) Run<A>(this Isotope<A> ma, IsotopeSettings settings = null) =>
            ma.WithEnv().Run(unit, settings);

        public static (IsotopeState state, A value) Run<A>(this Isotope<A> ma, IWebDriver driver, IsotopeSettings settings = null) =>
            ma.WithEnv().Run(unit, driver, settings);

        public static Isotope<Unit> setWindowSize(Size size) =>
            setWindowSize<Unit>(size).WithoutEnv();

        public static Isotope<Seq<IWebElement>> findElements(IWebElement parent, By selector, bool wait = true, string error = null) =>
            findElements<Unit>(parent, selector, wait, error).WithoutEnv();

        private static Isotope<Unit, A> WithEnv<A>(this Isotope<A> iso) =>
        (env, sa) =>
        {
            var a = iso(sa);
            return new IsotopeState<A>(a.Value, a.State);
        };

        private static Isotope<A> WithoutEnv<A>(this Isotope<Unit, A> iso) =>
            sa =>
            {
                var a = iso(unit, sa);
                return a;
            };
    }
}
```

**Comment by louthy** [comment]
@appetere @colethecoder 

The way to make this work would be to have two types:

```c#
    public delegate IsotopeState<A> Isotope<A>(IsotopeState state);
    public delegate IsotopeState<Env, A> Isotope<Env, A>(Env env, IsotopeState state);
```
Then write `Bind` that understands both, but the non-env one gets promoted to an env type when combined:
```c#
    public static Isotope<Env, B> Bind(this Isotope<Env, A> ma, Func<A, Isotope<Env, B>> f) =>
        ...;

    public static Isotope<B> Bind(this Isotope<A> ma, Func<A, Isotope<B>> f) =>
        ...;

    // This promotes to an Env type
    public static Isotope<Env, B> Bind(this Isotope<A> ma, Func<A, Isotope<Env, B>> f) =>
        ...;
```
Then you can formulate the LINQ functions:

```c#
public static Isotope<Env, C> SelectMany(this Isotope<Env, A> ma, Func<A, Isotope<Env, B>> bind, Func<A, B, C> select) =>
    ...;

public static Isotope<C> SelectMany(this Isotope<A> ma, Func<A, Isotope<B>> bind, Func<A, B, C> select) =>
    ...;

public static Isotope<Env, C> SelectMany(this Isotope<A> ma, Func<A, Isotope<Env, B>> bind, Func<A, B, C> select) =>
    ...;

```
Therefore functions that don't need an `Env` don't have to declare it.

**Comment by louthy** [comment]
Just to follow up, I do this for [`Aff<Env, A>`](https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/IO/Aff.cs#L600), [`Aff<A>`](https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/IO/AffPure.cs#L602), [`Eff<Env, A>`](https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/IO/Eff.cs#L472), and [`Eff<A>`](https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/IO/EffPure.cs) in language-ext.

**Comment by appetere** [comment]
Closing as superceded by https://github.com/meddbase/isotope80/pull/2

**Pull request closed without merging**
